### PR TITLE
added framework-pac.jar to BOOTCLASSPATH for all ramdisks

### PR DESCRIPTION
**Pull request by Efpophis**
Hi DT,

To make sure I got them all, I added the new JAR file to every BOOTCLASSPATH I could find under ramdisks/

I imagine there might be some where it's not needed, though - if you know which ones, post a comment before you merge, and I will happily remove them.

### CODE REVIEW

**Comment by Efpophis** [comment]
Ok, all fixed, sir.

**Comment by Efpophis** [comment]
Now that this is in, I'm curious about something.

I was not able to figure out by reading your source and build scripts how does your kernel decide which ramdisk to use?  It looks like there are several different possibilities under, for example, t0lte-combo, but when I flash that, how does my phone then realize that it should use the stuff under roms/cm102 ?

**Comment by DerTeufel** [comment]
Are you talking about the device specific Ramdisk, eg. T0lte or i9300, or do you mean the rom choice? The rom cho ice is made by init script (in /sbin)

**Comment by Efpophis** [comment]
I was talking about the rom choice - I see it now, thanks :)

**Pull request merged**
